version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: recipe_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: recipix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - recipe_network

networks:
  recipe_network:
    driver: bridge

volumes:
  postgres_data:
