#spring.application.name=RecipeApplication
#
#spring.jpa.open-in-view=false
#spring.jpa.show-sql=false
#
#server.port=8082
#spring.datasource.url=jdbc:postgresql://localhost:5432/recipix
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.hibernate.ddl-auto=create-drop

spring:
  application:
    name: RecipeApplication

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/recipix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

jwt:
  secret-key: ec6b682bc2523c4c882ca4172b09b4242715519bef277eecdc0608bf8c20f88aaa52393ee04011f46de93b85f1f329eafaa66292727b508093d814f13da220b7
  expiration: 86400000
  refresh-token:
    expiration: 604800000
